'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibonacci():
    """Fibonacci numbers generator"""
    a, b = 1, 2
    while True:
        yield a
        a, b = b, a + b

f = fibonacci()

fib_list = []
for x in f:
    if (x > 4000000):
        break 
    else:
        if x % 2 == 0:
            fib_list.append(x)
print sum(fib_list)
